# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gitsubmodule" # See documentation for possible values
    directory: "/themes/" # Location of package manifests
    schedule: 
      interval: "daily" 
      time: "16:45" 
      timezone: "Europe/Paris"
    open-pull-requests-limit: 10
